/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox.ray;

import org.junit.Test;

import static org.junit.Assert.*;

public class LoxTest {
    @Test
    public void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void printExpr() {
        Expr expression = new Expr.Binary(
                new Expr.Unary(
                        new Token(TokenType.MINUS, "-", null, 1),
                        new Expr.Literal(123)
                ),
                new Token(TokenType.STARA, "*", null, 1),
                new Expr.Grouping(
                        new Expr.Literal(45.67)
                )
        );
        // (* (- 123) (group 45.67))
        System.out.println(new AstPrinter().print(expression));
    }
}
