/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox.ray;

import org.junit.Test;
import static org.junit.Assert.*;

public class LoxTest {
    @Test public void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
