/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox.ray;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        if (args.length > 1) {
            System.out.println("Usage: jlox [script]");
            System.exit(64);
        } else if (args.length == 1) {
            // runFile(args[0]);
        } else {
            // runPrompt();
        }
    }
}
